### ISSUE TITLE
box-sizing: border-box; Returns width without border and padding

### ISSUE THREAD

**Issue by StephenEsser** [que-etc/resize-observer-polyfill#11]
After updating the box-sizing to border-box in my application all the existing functionality I was utilizing from this project started being inconsistent because of padding and borders. 

```
// Normalize box-sizing.
// More info: https://css-tricks.com/box-sizing/#article-header-id-6
html {
  box-sizing: border-box;
}
```

Is there a way to request the width returned to include these? Or calculate these manually? I noticed some of the doc examples call out padding, but I don't see a way to calculate width + padding + borders with what is returned. 

Currently I am getting the offsetWidth from the target, but asking for this property causes a reflow every time they are accessed.

**Comment by que-etc** [comment]
Unfortunately, ResizeObserver calculates and tracks only the content-box of an element and there is no way you can make it work with any other box-model. FYI, I've already [suggested](https://github.com/WICG/ResizeObserver/issues/34#issuecomment-279444681) extending it with an optional parameter which would specify what kind of a box-model needs to be observed.

For the being, you can't avoid extra reflows if you need to calculate the border-box of an element. I figure that the offset[width/height] properties are your best option here, unless you want to retrieve non-rounded values or to have them with CSS transformations. In such case, stick with the `getBoundingClientRect`.
