### ISSUE TITLE
Doesn't detect size changes on `:hover`

### ISSUE THREAD

**Issue by FezVrasta** [que-etc/resize-observer-polyfill#12]
If I have an element with:

```
.element:hover {
  width: 200px;
}
```

This library will not detect the size change when I hover over it.

**Comment by que-etc** [comment]
@FezVrasta  You can pick up the `hover` event but only if it starts a transition. Please, take a look at this [example](https://jsfiddle.net/que_etc/7fudzqng/) to get how to trigger notifications when hover changes the size of an element.

It's a know issue which is already mentioned in readme :)

**Comment by FezVrasta** [comment]
I see, thank you.
