### ISSUE TITLE
Unobserve on node removal

### ISSUE THREAD

**Issue by ZeeCoder** [que-etc/resize-observer-polyfill#15]
Hey, it might be obvious, but I'm not entirely sure if I need to explicitly unobserve elements removed from the DOM to avoid memory leaks or not?

**Comment by que-etc** [comment]
Hi.

Yes, it's advisable to remove elements from the observations list if you don't want them to be observed any longer. So, unless you plan to add a detached element back to the DOM ([sample](https://jsfiddle.net/que_etc/u76ygbvt/)), you should "unobserve" it.

This might not be a big deal in case of the native implementation, as it leverages weak references, but on the JS side we only have Weak[Map/Set] collections which are not particularly instrumental here as they can't be iterated.

That is, if you don't remove an unused element, it will lead to memory leaks.

**Comment by ZeeCoder** [comment]
That's what I thought, thanks!
I'll just observe element removals and unobserve them automatically.

Cheers :+1:

**Comment by que-etc** [comment]
@ZeeCoder 

> I'll just observe element removals and unobserve them automatically.

Just a tip. If you want to be notified of an element's removal, you may not need to add an extra MutationObserver. In case an element is not empty or hidden, you may as well use RO to detect when it's being removed from DOM.

```javascript
new ResizeObserver((entries, observer) => {
    const entry = entries[0];
    const target, {rect = contentRect} = entry;

    if (!rect.width && !rect.height && !document.body.contains(target)) {
        console.log('element is detached');
        observer.unobserve(target);
    }
});
```

**Comment by ZeeCoder** [comment]
That's an interesting idea, though I'd rather go with a foolproof solution.
I've already implemented 90% of the MutationObserver version anyway. :D
