### ISSUE TITLE
Maybe Undo MutationEvent Fix For IE11?

### ISSUE THREAD

**Issue by paulie4** [que-etc/resize-observer-polyfill#19]
I tested https://jsfiddle.net/x2r3jpuz/2/ on IE11, and it is not causing a crash for me. This is the version info for my IE11:
![image](https://user-images.githubusercontent.com/203125/30083535-c9ee7202-925c-11e7-8c4b-0214e5c8e1dc.png)

If Microsoft has apparently fixed whatever bug was causing that problem, should the code switch back to using MutationObservers instead of MutationEvents, since [MDN's docs](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent#Performance) say MutationEvents are deprecated and can make DOM modifications "1.5 - 7 times slower?"

**Comment by que-etc** [comment]
@paulie4 

Well, considering that it's been a while since v11.0.43 was released, I believe that it's safe to enable MutationObserver for IE again.

Thank you for letting me know and especially for your patience!

**Comment by que-etc** [comment]
Fixed in [v1.5.0](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.5.0)
