### ISSUE TITLE
"Unreachable code" error in ResizeObserver.js

### ISSUE THREAD

**Issue by occamsraiser** [que-etc/resize-observer-polyfill#21]
Hey folks. I get a build warning with webpack when using this polyfill:

build     │ Dropping unreachable code [./\~/resize-observer-polyfill/dist/ResizeObserver.js:1010,0]
build     │ Declarations in unreachable code! [./\~/resize-observer-polyfill/dist/ResizeObserver.js:1010,0]

Looks like lines 1010 and 1009 should be flipped
<img width="646" alt="reactobserverlines1005to1014" src="https://user-images.githubusercontent.com/6416011/30140436-c67320e8-9331-11e7-94c9-df6a0f24c749.png">

**Comment by que-etc** [comment]
Seems like this warning is raised by UglifyJS. Unfortunately, I can't do much about it because this code is auto-generated.

I can only say that it doesn't remove the `var ref;` declaration and that there is no reason to worry because declarations are handled before the execution stage.
