### ISSUE TITLE
Travis Automatic PR Build Issue

### ISSUE THREAD

**Issue by c0un7-z3r0** [que-etc/resize-observer-polyfill#26]
Travis PR builder seems to have been failing due to `SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables are not defined.`

@que-etc Not sure how to fix this

**Comment by que-etc** [comment]
Thanks!

I'll add an extra environment for pull request which will run tests in Firefox instead of a whole sauce stack.

**Comment by que-etc** [comment]
Fixed in [v1.5.0](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.5.0)
