### ISSUE TITLE
Infinite loop causes tab to crash

### ISSUE THREAD

**Issue by eric-simonton-sama** [que-etc/resize-observer-polyfill#27]
I originally filed this issue with [`ngx-bootstrap`](https://github.com/valor-software/ngx-bootstrap) because I discovered it when triggered by their tooltips. (Actually, our users discovered it in production 😞 ) However, after much investigation, I found it was the combination of their tooltips, this library, and browser zooming that all have to come together to trigger the issue.

Here is [a plnkr](https://plnkr.co/edit/AmW3X3qnImq3njEnFwAg?p=preview) demonstrating the issue. Zoom the browser in or out and mouse over the buttons to lock up the browser tab as it spikes the CPU in some kind of infinite loop. You may need to experiment: for me on Chrome it locks up at 90% and 125% zoom, but not at 100% or 110%.

[Here](https://github.com/valor-software/ngx-bootstrap/issues/3047) is same the issue I filed with `ngx-bootstrap`. I'm not sure which library is to blame, so I'm also filing this issue as well in case there is something to fix here.

**Comment by que-etc** [comment]
@eric-simonton-sama 

I've managed to trace it down to MutationObserver and [Line 104](https://github.com/angular/zone.js/blob/v0.7.2/dist/zone.js#L104) zone.js. Here is an updated [code](https://plnkr.co/edit/L2MBDBNCk53AQcxHGe5c?p=preview) which doesn't use ResizeObserver.

**Comment by que-etc** [comment]
Updating to v0.8.18 didn't help. For the time being, looks like it's a problem with zone.js

**Comment by que-etc** [comment]
Yeap, problem is definitely on the zone's side.

In this [example](https://plnkr.co/edit/Km6NR2?p=preview) any [modifications](https://github.com/angular/zone.js/blob/v0.8.18/dist/zone.js#L2861) to MutationObserver are disabled and everything works smoothly.

**Comment by eric-simonton-sama** [comment]
Thank you for this investigation! I'll close this issue and open one with `zone.js` instead.
