### ISSUE TITLE
Firefox 57 Linux not working

### ISSUE THREAD

**Issue by themre** [que-etc/resize-observer-polyfill#28]
This page: https://que-etc.github.io/resize-observer-polyfill/ works on FF 56.0.2 on Linux, but not version 57.

**Comment by HolgerJeromin** [comment]
Firefox 57 on Windows 7 renders the page.

**Comment by que-etc** [comment]
@themre 

Could you please provide more information about the issue? What does console show, if anything, or maybe a screenshot of the page.

As @HolgerJeromin already mentioned, everything works in FF 57 (windows 10) and I also can't see any problems in v57 for Android 8.1.

**Comment by que-etc** [comment]
@HolgerJeromin 

Does anything else happen apart from the page being rendered?
I mean it should do something like [this](http://nmotw.in/images/resize-observer-polyfill/resize-observer-polyfill.gif).

**Comment by HolgerJeromin** [comment]
yes, the animation is shown.

**Comment by themre** [comment]
Yes, on Windows it works, only Linux distribution is the problem. I'll ask coworker to look into more detailed error, since I don't have linux with me. It is also shown, that this feature is still in development: https://bugzilla.mozilla.org/show_bug.cgi?id=1272409

**Comment by que-etc** [comment]
FYI, that demo page is configured to use only the pollyfill's implementation of ResizeObserver no matter what host object is available.

So, if this exact page doesn't work in some browser, than it's definitely something wort looking into and most likely a pollyfill's issue.

Thanks, I'll wait until then and probably install Linux on my machine.

**Comment by themre** [comment]
We tried in our app and the demo. On Wins it works in both cases, with Linux it fails on both. Sure, no problem, I'll provide you with detailed error tomorrow. Thanks!

**Comment by themre** [comment]
apparently there was misunderstanding. your demo works also on Firefox on Linux, but apparently problem occurs before and also fires errors regarding ResizeObserver. Sorry for the false alarm!
