### ISSUE TITLE
Misleading filenames

### ISSUE THREAD

**Issue by tfmontague** [que-etc/resize-observer-polyfill#3]
https://github.com/que-etc/resize-observer-polyfill/blob/master/dist/ResizeObserver.js
https://github.com/que-etc/resize-observer-polyfill/blob/master/dist/ResizeObserver.global.js

Please rename to:
- ResizeObserver.min.js
- ResizeObserver.global.min.js

**Comment by que-etc** [comment]
Will do. Thanks.

**Comment by que-etc** [comment]
Fixed in [1.1.4](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.1.4) version.
