### ISSUE TITLE
Add this polyfill to polyfill.io

### ISSUE THREAD

**Issue by TristanPct** [que-etc/resize-observer-polyfill#33]
Hello and thanks for this pollyfill!

I have a little question: have you considered adding this polyfill to [polyfill.io](https://github.com/Financial-Times/polyfill-service)?

**Comment by ZeeCoder** [comment]
And core-js? 🤔
Then I could insert it automatically with babel-preset-env :D

**Comment by radeno** [comment]
@ZeeCoder i think you missed what polyfill.io really offers. Dynamic polyfills. Core-JS is about prepackaging features with static polyfills for all browsers. Yes even for that which have native implementation. And that is that point of polyfill.io. Send only what is needed.

**Comment by ishpagin** [comment]
So? When? 💃

**Comment by TristanPct** [comment]
With the v3 of polyfill.io this polyfill is now available !

https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver

**Comment by aloiseau17** [comment]
And about `core-js` is it available ?
