### ISSUE TITLE
​​TypeError: Right-hand side of 'instanceof' is not an object​​

### ISSUE THREAD

**Issue by ablamunits** [que-etc/resize-observer-polyfill#34]
Hi,

I am using [jsdom-global](https://github.com/rstacruz/jsdom-global) when running tests and I am receiving the following error when using `ResizeObserver`:

```
​​TypeError: Right-hand side of 'instanceof' is not an object​​
```

I tracked down the problem to [this line](https://github.com/que-etc/resize-observer-polyfill/blob/3e689695e0fff99b15f3cbaf833c3c3ede6d33b9/src/utils/geometry.js#L164) in the `isSVGGraphicsElement` function:

```
...
return target => (
    target instanceof getWindowOf(target).SVGElement &&
    typeof target.getBBox === 'function'
);
```

It seems that `SVGElement` is possibly not defined on the window. Would adding a check to see if `SVGElement` is defined interfere with the functionality here in any way?
To be honest I am not quite sure if this is an issue with the polyfill or rather with me using jsdom. I would be happy to have some guidance here and contribute if I can.

Thanks!

**Comment by HolgerJeromin** [comment]
As the function is only called in this check 
https://github.com/que-etc/resize-observer-polyfill/blob/3e689695e0fff99b15f3cbaf833c3c3ede6d33b9/src/utils/geometry.js#L190-L194
It seems to be "future proof" (past proof? :) to check for SVGElement and return false if this is not available. So the code for HTML handling will be called which seems a good solution.
