### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by Karnakark** [que-etc/resize-observer-polyfill#36]
Hi, Thanks for this awesome resize polyfill.

Can you please confirm whether it is compatible with angular 6.x?. This polyfill is working in both chrome and IE with angular 5.x. I recently updated my app from angular5.x to 6.x. and found out that resize polyfill seems to be not working in IE. Any help.

**Comment by TrySound** [comment]
@Karnakark This polyfill doesn't have any angular specific things. Maybe the problem is rxjs connection. How exactly do you use this plugin?

**Comment by Karnakark** [comment]
I have a chart inside a div, I would like to resize chart depends on div size. 
import ResizeObserver from 'resize-observer-polyfill';
private _ro: ResizeObserver;
private _elem;
ngOnInIt() {
    this._ro= new ResizeObserver((entries, observer) => {
     if (this._chart  && this._chart.container) {
        this._chart.reflow();
       }
     });
   this._elem= this.elRef.nativeElement.parentElement
        ? this.elRef.nativeElement.parentElement
        : document.body;
//this.elem is parent element of my chart svg element
  this._ro.observe(this._elem);
}
constructor(private elRef: ElementRef) {
}

**Comment by lucipacurar** [comment]
Actually, inside my app crashes on Safari 11 and macOS 10.13 when running the ResizeObserver. To avoid the crash you must run the observer outside the ngZone like this:

```ts
public ro = new ResizeObserver(entries => {
        for (const entry of entries) {
            this.ngZone.run(() => {
                // code here
            });
        }
    });

ngAfterViewInit() {
        // Safari crashes if we run the observer inside the Angular Zone
        this.ngZone.runOutsideAngular(() => {
            this.ro.observe(this.headerSection.nativeElement);
        });
    }
```
