### ISSUE TITLE
Typescrpt Definition do not expose global ResizeObservable.

### ISSUE THREAD

**Issue by marlon-tucker** [que-etc/resize-observer-polyfill#37]
At the moment, for Typescript to see the `ResizeObservable` constructor, it has to be imported from the module, however this library is meant to be a polyfill so it should expose the variable globally so the `resize-observer-polyfill` module can be referenced in the `types` property in the `tsconfig.json` file. 

The definition file needs to be changed to look like this:

```
interface DOMRectReadOnly {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    readonly top: number;
    readonly right: number;
    readonly bottom: number;
    readonly left: number;
}

declare global {
    interface ResizeObserverCallback {
        (entries: ResizeObserverEntry[], observer: ResizeObserver): void
    }

    interface ResizeObserverEntry {
        readonly target: Element;
        readonly contentRect: DOMRectReadOnly;
    }

    interface ResizeObserver {
        observe(target: Element): void;
        unobserve(target: Element): void;
        disconnect(): void;
    }

    const ResizeObserver: {
        prototype: ResizeObserver;
        new(callback: ResizeObserverCallback): ResizeObserver;
    }
}

export default ResizeObserver;
```

Just a minor change really, moving the `const ResizeObserver` declaration inside the global declaration.

**Comment by TrySound** [comment]
Think the name is bad. This is actually a ponyfill. There is not need in this change.
https://github.com/que-etc/resize-observer-polyfill/blob/master/src/index.js

**Comment by marlon-tucker** [comment]
ahh ok I see, thank you for the clarification.
