### ISSUE TITLE
How to externalise resize-observer-polyfill in Webpack

### ISSUE THREAD

**Issue by teneko** [que-etc/resize-observer-polyfill#42]
I have a currently a problem with a simple externalization in Webpack.

My module (@teronis-js/event-driven-resize-observer-polyfill) is bundled with webpack and these externals:
```
...
externals: {
      "@teronis-js/event-dispatcher": {
        commonjs: "@teronis-js/event-dispatcher",
        commonjs2: "@teronis-js/event-dispatcher",
        amd: "@teronis-js/event-dispatcher",
        root: ["Teronis", "EventDispatcher"],
      },
      "resize-observer-polyfill": "resize-observer-polyfill"
    }
...
```

The module and their dependencies are included in my frontend app like that :
```
...
<script src="node_modules/@teronis-js/event-dispatcher/dist/teronis-js-event-dispatcher.js"></script>
<script src="node_modules/resize-observer-polyfill/dist/ResizeObserver.js"></script>
<script src="node_modules/@teronis-js/event-driven-resize-observer-polyfill/dist/teronis-js-event-driven-resize-observer-polyfill.js"></script>
...
```

Current behavior when invoking the index html with scripts:
Uncaught TypeError: resize_observer_polyfill__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor

I know that the resize-observer-polyfill is not built by webpack and I think that the head of the /dist/ResizeObserver.js belongs to commonjs and amd. I may be wrong with this.

I am pretty new in the world of Webpack and so I would like to ask you how I could externalise this polyfill.

**Comment by que-etc** [comment]
@teroneko have you tried adding the `root` option to your webpack config? 

```javascript
{
    externals: {
        "resize-observer-polyfill": {
            root: "ResizeObserver"
        }
    }
}
```
