### ISSUE TITLE
Firefox throws error for ResizeObserverSPI.prototype.observe function

### ISSUE THREAD

**Issue by chunminglu** [que-etc/resize-observer-polyfill#46]
In firefox it throws error in ResizeObserverSPI.prototype.observe function, saying `TypeError: "invalid 'instanceof' operand getWindowOf(...).Element"`. 

Try to watch `getWindowOf(target)`, and it returns
`{​
    __impl4cf1e782hg__: Window,
    <prototype>: {…}
}` instead of `window` directly.

**Comment by que-etc** [comment]
Could you provide a self-contained example on jsfiddle or codepen?

**Comment by chunminglu** [comment]
Ok nvm. I think the reason is because of webcomponent polyfill in firefox...
