### ISSUE TITLE
WeakMap Polyfill Causes Syntax Error when Uglifying

### ISSUE THREAD

**Issue by robwise** [que-etc/resize-observer-polyfill#5]
I'm running into a strange error that seems to be pointing at this polyfill's use of a WeakMap polyfill when I try to run my build with Webpack and have the Uglifier plugin enabled. There's no problem when not uglifying.

```
ERROR in app-4104c5d067f2dcfdce5d.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [app-4104c5d067f2dcfdce5d.js:43608,18]
```

If I open my compiled babel output to that line, it's pointing at this line here: https://github.com/que-etc/resize-observer-polyfill/blob/master/src/shims/es6-collections.js#L15

What's interesting is it's still es6 (fat arrow) and not compiled to an es5 function:

```js
const WeakMap = (() => {
```

Related Issues:
https://github.com/webpack/webpack/issues/3453
https://github.com/souporserious/react-measure/issues/29

Webpack build is 2.1.0-beta.22
resize-observer-polyfill is 1.2.1
react-measure is 1.4.4

**Comment by robwise** [comment]
Changing babel-loader like this has now resolved this, closing, but hope this helps someone with same issue.


Before (errors):

```js
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node-modules/,
        query: {
          cacheDirectory: true,
        },
      },
```

After (works):

```js
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        query: {
          cacheDirectory: true,
        },
      },
```

Note that using an `include` seems to break it also:

```js
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        include: /src/,
        query: {
          cacheDirectory: true,
        },
      },
```

**Comment by que-etc** [comment]
Webpack 2 takes the ES6 modules version of a package if it has a `module` field in its package.json file. And I'm afraid that this is a misuse of this field from my side as I'm shipping a non-transpiled ES6 code under it.

**Comment by que-etc** [comment]
Fixed in v. 1.3.0
