### ISSUE TITLE
MutationObserver in IE11 causing exceptions

### ISSUE THREAD

**Issue by jrsearles** [que-etc/resize-observer-polyfill#6]
I am seeing issues with this polyfill in IE11, which appear to be caused by the MutationObserver instance. I haven't been able to create an isolated reproduction, but when the issue occurs the entire browser crashes.

I was wondering if it might be feasible to add an option to disable the use of the MutationObserver? That way we could disable it conditionally in our application.

**Comment by que-etc** [comment]
Weird, I haven't encountered this problem in tests. Though a quick search suggests that it has something to with the `<table>` element. Is this your case?

I will certainly look into this.

**Comment by que-etc** [comment]
I'm afraid I'm not able to tackle this problem by any other means but disabling the MustationObserver for IE completely as it's being unreliable. And I don't want to make it configurable because this is a bad option for an end user of a third-party library.

I'll release a patch asap.

**Comment by jrsearles** [comment]
Great - appreciate that. I agree that disabling it for IE is a better option. My case wasn't with a table - it seemed to be with removing and readding elements to the DOM, though i wasn't able to reproduce it in isolation.

**Comment by que-etc** [comment]
Fixed in [v1.4.0](https://github.com/que-etc/resize-observer-polyfill/releases/tag/1.4.0).

@jrsearles Feel free to let me if this crash still exists in your case. And once again, thanks for filing this bug!

**Comment by jrsearles** [comment]
That solved the problem - thanks for the quick response!
