### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by tobireif** [que-etc/resize-observer-polyfill#61]
Great polyfill!

Unfortunately I just found out that it doesn't work at all in Safari.

Can you make it work in Safari?

**Comment by lazysergey** [comment]
@tobireif same here safari 13.0.5 - how did you solve this?

**Comment by tobireif** [comment]
For this https://tobireif.com/posts/layout_fun_with_css_grid/
I use https://github.com/que-etc/resize-observer-polyfill
minus throttling.

It works beautifully in all modern browsers including Safari. I guess that's why I had closed the ticket.

Perhaps your Safari is outdated?

In any case, you did find an issue, best to submit a new ticket / bug report.
