### ISSUE TITLE
Question: Can the resize observer optionally bind to observe window resize events.

### ISSUE THREAD

**Issue by StephenEsser** [que-etc/resize-observer-polyfill#8]
There are cases in my project where I'd like to conditionally observe resize events on specific elements or the window. Currently the ResizeObserver throws and error because the window is not of type element.

I was just curious if it was possible for this to work, otherwise I'll split the functionality into different logic blocks to do a traditional resize listener on the window in those special cases.

**Comment by que-etc** [comment]
@StephenEsser, it observes only Element instances and unfortunately there is no way to directly subscribe for the window object.

I've been trying to think of any workaround that would utilize the documentElement (`<html>`) or the body element but they all observe completely different rectangles. This is what I ended up with:
```javascript
var tmpl =
    '<div id="TARGET" style="' +
        'width: 100vw;' + 
        'height: 100vh;' +
        'position: absolute;' + 
        'top: -100vh;">' + 
    '</div>';

document.body.insertAdjacentHTML('beforeend',  tmpl)

var observer = new ResizeObserver(function (entries) {
    console.log(entries[0].contentRect); 
});

observer.observe(TARGET);
```
It requires to create an extra element which covers the whole viewport area. I don't think that this exact code is anyway close to being crossbrowser, but it's certainly possible  to make it work in something like IE9.

So, to round up, I believe that subscribing to the window's `resize` event is the best option in your case.

**Comment by StephenEsser** [comment]
@que-etc, Thanks for the quick reply, I'll continue forward with binding directly on the window. Thanks again.
